// SPDX-License-Identifier: Apache-2.0
/**
 * Chat state store — messages, streaming, violations, ask flow, stop.
 * Svelte 5 runes mode. Must be .svelte.ts.
 *
 * Components read from the exported `state` object (proxy-tracked property
 * access) rather than getter functions, so Svelte's reactivity system
 * reliably tracks cross-module dependencies.
 */

import { api } from '$lib/api';
import { normalizeAssistantContent } from '$lib/normalize';
import { formatAttachmentContext, baseName } from '$lib/attachments';
import type { ChatMessage, ChatStreamDelta, ChatStreamEnd, ChatFileActionEvent, ModelInfo, PendingViolation, AskRequest, FileAttachment, AttachFileResult, ConversationMeta, ConversationData } from '$shared/types';
import { generateTitle, toPersistedMessage, fromPersistedMessage } from '$shared/conversation-utils';

// --- State ---

let messages = $state<ChatMessage[]>([]);
let pendingAttachments = $state<FileAttachment[]>([]);
const stoppedStreams = new Set<string>();

// Conversation state
let conversationId = $state<string | null>(null);
let conversationTitle = $state('');
let conversationList = $state<ConversationMeta[]>([]);
let conversationCreatedAt = $state(0);
let titleAutoGenerated = $state(false);
let titleManuallySet = $state(false);

/**
 * Exported reactive state object.  Components read properties directly
 * (e.g. `chat.state.streaming`) which ensures Svelte's proxy tracks the
 * dependency — unlike getter functions which can snapshot the value.
 */
export const state = $state({
  streaming: false,
  currentStreamId: null as string | null,
  pendingViolation: null as PendingViolation | null,
  selectedModel: '',
  availableModels: [] as ModelInfo[],
  error: null as string | null,
  pendingAsk: null as AskRequest | null,
  /** Last user message text that failed to send — for retry */
  lastFailedMessage: null as string | null,
});

// --- Derived ---

const canSend = $derived(!state.streaming && !state.pendingViolation);

// --- Getters (for components) ---

export function getMessages(): ChatMessage[] { return messages; }
export function getCanSend(): boolean { return canSend; }
export function getPendingAttachments(): FileAttachment[] { return pendingAttachments; }
export function getConversationId(): string | null { return conversationId; }
export function getConversationTitle(): string { return conversationTitle; }
export function getConversationList(): ConversationMeta[] { return conversationList; }

// --- Actions ---

let nextMsgId = 1;
function msgId(): string {
  return `msg-${nextMsgId++}`;
}

export async function send(content: string): Promise<void> {
  const hasText = content.trim().length > 0;
  const snapshot = [...pendingAttachments];
  if (!canSend || (!hasText && snapshot.length === 0)) return;

  state.error = null;
  state.lastFailedMessage = null;

  // Clear pending attachments immediately (content freed from memory)
  pendingAttachments.length = 0;

  // Build message content: attachments + user text
  const messageContent = snapshot.length > 0
    ? formatAttachmentContext(snapshot, content)
    : content.trim();

  // Add user message with optional attachment metadata
  const userMsg: ChatMessage = {
    id: msgId(),
    role: 'user',
    content: hasText ? content.trim() : '',
    timestamp: Date.now(),
  };
  if (snapshot.length > 0) {
    userMsg.attachments = snapshot.map(a => ({ name: a.name, size: a.size }));
  }
  messages.push(userMsg);

  // Auto-title on first send (uses original user text, not attachment-expanded).
  // Only runs once. If user manually renamed, titleManuallySet is true → skip.
  if (!conversationTitle && !titleManuallySet) {
    const attachNames = snapshot.length > 0 ? snapshot.map(a => a.name) : undefined;
    conversationTitle = generateTitle(content.trim(), attachNames);
    titleAutoGenerated = true;
  }

  state.streaming = true;

  try {
    // Start streaming — inject attachment content into the last user message
    const history = messages
      .filter(m => m.role === 'user' || m.role === 'assistant')
      .map(m => ({ role: m.role, content: m.content }));
    // Override last user message with full content (attachments + text)
    if (history.length > 0 && history[history.length - 1].role === 'user') {
      history[history.length - 1].content = messageContent;
    }
    const { streamId } = await api.chatStreamStart(
      history,
      state.selectedModel ? { model: state.selectedModel } : {},
    );
    state.currentStreamId = streamId;

    // Add placeholder assistant message
    messages.push({
      id: msgId(),
      role: 'assistant',
      content: '',
      timestamp: Date.now(),
      streaming: true,
    });
  } catch (err) {
    state.streaming = false;
    state.error = String(err);
    state.lastFailedMessage = content;
    // Remove the user message that was added before the error
    const lastMsg = messages[messages.length - 1];
    if (lastMsg?.role === 'user') {
      messages.pop();
    }
  }
}

export function onDelta(data: ChatStreamDelta): void {
  if (data.streamId !== state.currentStreamId || stoppedStreams.has(data.streamId)) return;
  const last = messages[messages.length - 1];
  if (last?.role === 'assistant' && last.streaming) {
    last.content += data.delta.content ?? '';
  }
}

export function onEnd(data: ChatStreamEnd): void {
  if (data.streamId !== state.currentStreamId) return;
  const last = messages[messages.length - 1];
  if (last?.role === 'assistant') {
    last.content = normalizeAssistantContent(last.content);
    last.streaming = false;
    last.receipt = data.result.receipt ?? null;
    last.violations = data.result.violations ?? [];
    if (data.result.fileActions) {
      last.fileActions = data.result.fileActions;
    }
    if (data.result.pending) {
      state.pendingViolation = data.result.pending;
    }

    // If the stream ended with no content but has violations, treat as an error.
    // This happens when the daemon returns an RPC error (auth, rate limit, etc.)
    // that gets caught by the tool loop's error handler.
    if (!last.content && last.violations.length > 0 && !last.receipt) {
      const errorDesc = last.violations[0]?.description ?? 'An error occurred';
      state.error = errorDesc;
      state.lastFailedMessage = messages.length >= 2 ? messages[messages.length - 2]?.content ?? null : null;
      // Remove the empty assistant message
      messages.pop();
    }
  }
  if (data.streamId) stoppedStreams.delete(data.streamId);
  state.streaming = false;
  state.currentStreamId = null;
  state.pendingAsk = null;

  // Auto-save after stream completes
  saveCurrentConversation();
}

export function onFileAction(data: ChatFileActionEvent): void {
  if (data.streamId !== state.currentStreamId || stoppedStreams.has(data.streamId)) return;
  const last = messages[messages.length - 1];
  if (last?.role === 'assistant') {
    if (!last.fileActions) last.fileActions = [];
    last.fileActions.push(data.action);
  }
}

export function onAskRequest(data: AskRequest): void {
  if (data.streamId !== state.currentStreamId || stoppedStreams.has(data.streamId)) return;
  state.pendingAsk = data;
}

export async function respondToAsk(decision: 'allow_once' | 'deny'): Promise<void> {
  if (!state.pendingAsk) return;
  const ask = state.pendingAsk;
  state.pendingAsk = null;
  try {
    await api.askRespond(ask.askId, decision);
  } catch (err) {
    state.error = String(err);
  }
}

export async function stopStreaming(): Promise<void> {
  if (!state.streaming || !state.currentStreamId) return;
  stoppedStreams.add(state.currentStreamId);
  try {
    await api.chatStreamStop(state.currentStreamId);
  } catch {
    // Best effort
  }
}

export async function resolveViolation(action: 'fix' | 'revise' | 'proceed', param?: string): Promise<void> {
  if (!state.pendingViolation) return;

  try {
    switch (action) {
      case 'fix':
        await api.commitFix(param);
        break;
      case 'revise':
        await api.commitRevise();
        break;
      case 'proceed':
        await api.commitProceed(param ?? 'User approved');
        break;
    }
    state.pendingViolation = null;
  } catch (err) {
    state.error = String(err);
  }
}

export function setModel(model: string): void {
  state.selectedModel = model;
}

export async function loadModels(): Promise<void> {
  try {
    state.availableModels = await api.chatModels();
    if (state.availableModels.length > 0 && !state.selectedModel) {
      state.selectedModel = state.availableModels[0].id;
    }
  } catch {
    state.availableModels = [];
  }
}

export function clearError(): void {
  state.error = null;
  state.lastFailedMessage = null;
}

export function retry(): void {
  if (!state.lastFailedMessage) return;
  const msg = state.lastFailedMessage;
  state.error = null;
  state.lastFailedMessage = null;
  send(msg);
}

// --- Attachment actions ---

const MAX_ATTACHMENTS = 5;

export async function attachFile(absolutePath: string): Promise<AttachFileResult> {
  const name = baseName(absolutePath);

  // Dedupe by path
  if (pendingAttachments.some(a => a.path === absolutePath)) {
    return { ok: true, attachment: pendingAttachments.find(a => a.path === absolutePath)! };
  }

  // Cap at 5
  if (pendingAttachments.length >= MAX_ATTACHMENTS) {
    return { ok: false, name, error: `Can't attach more than ${MAX_ATTACHMENTS} files.` };
  }

  const result = await api.readAbsoluteFile(absolutePath);
  if (!result.ok) {
    return { ok: false, name, error: result.error };
  }

  const attachment: FileAttachment = {
    name,
    path: absolutePath,
    size: result.size,
    content: result.content,
    contentHash: result.contentHash,
  };
  pendingAttachments.push(attachment);
  return { ok: true, attachment };
}

export function removeAttachment(path: string): void {
  const idx = pendingAttachments.findIndex(a => a.path === path);
  if (idx !== -1) pendingAttachments.splice(idx, 1);
}

export function clearAttachments(): void {
  pendingAttachments.length = 0;
}

export function clearMessages(): void {
  messages.length = 0;
  state.error = null;
  state.pendingViolation = null;
  state.pendingAsk = null;
}

// --- Conversation management ---

function uuid(): string {
  return crypto.randomUUID();
}

function hasSentMessages(): boolean {
  return messages.length > 0;
}

function buildConversationData(): ConversationData {
  // JSON round-trip strips Svelte 5 reactive proxies so the object
  // can pass through Electron's structured-clone IPC boundary.
  return JSON.parse(JSON.stringify({
    id: conversationId!,
    title: conversationTitle || 'Untitled',
    createdAt: conversationCreatedAt || Date.now(),
    updatedAt: Date.now(),
    messages: messages.map(toPersistedMessage),
  }));
}

export async function loadConversationList(): Promise<void> {
  try {
    const result = await api.conversationList();
    conversationList = result.conversations;
  } catch {
    conversationList = [];
  }
}

export async function restoreActiveConversation(): Promise<void> {
  try {
    const result = await api.conversationList();
    conversationList = result.conversations;

    if (result.activeId) {
      const loadResult = await api.conversationLoad(result.activeId);
      if (loadResult.ok) {
        conversationId = loadResult.conversation.id;
        conversationTitle = loadResult.conversation.title;
        conversationCreatedAt = loadResult.conversation.createdAt;
        messages.length = 0;
        messages.push(...loadResult.conversation.messages.map(fromPersistedMessage));
        titleAutoGenerated = false;
        // If it already has a title, treat it as set (don't auto-overwrite)
        titleManuallySet = !!loadResult.conversation.title;
        return;
      }
    }
  } catch {
    // Fall through to blank
  }

  // Create renderer-only blank
  conversationId = uuid();
  conversationTitle = '';
  conversationCreatedAt = Date.now();
  titleAutoGenerated = false;
  titleManuallySet = false;
  messages.length = 0;
}

export async function saveCurrentConversation(): Promise<void> {
  if (!conversationId || !hasSentMessages()) return;
  try {
    const data = buildConversationData();
    const result = await api.conversationSave(data);
    if (result.ok) {
      // Update local list
      const idx = conversationList.findIndex(c => c.id === conversationId);
      if (idx >= 0) {
        conversationList[idx] = result.meta;
      } else {
        conversationList.push(result.meta);
      }
      // Persist as active so it restores on restart
      await api.conversationSetActive(conversationId);
    }
  } catch {
    // Best-effort save
  }
}

export async function newConversation(): Promise<void> {
  if (state.streaming) return;

  // Save current if non-empty
  if (conversationId && hasSentMessages()) {
    await saveCurrentConversation();
  }

  // Create new blank
  conversationId = uuid();
  conversationTitle = '';
  conversationCreatedAt = Date.now();
  titleAutoGenerated = false;
  titleManuallySet = false;
  messages.length = 0;
  pendingAttachments.length = 0;
  state.error = null;
  state.pendingViolation = null;
  state.pendingAsk = null;

  // Add placeholder so sidebar shows immediately (before first save)
  conversationList.push({
    id: conversationId,
    title: '',
    createdAt: conversationCreatedAt,
    updatedAt: conversationCreatedAt,
    messageCount: 0,
  });
}

export async function switchConversation(id: string): Promise<void> {
  if (state.streaming) return;
  if (id === conversationId) return;

  // Save current if non-empty
  if (conversationId && hasSentMessages()) {
    await saveCurrentConversation();
  }

  // Load target
  const result = await api.conversationLoad(id);
  if (!result.ok) {
    state.error = result.error;
    return;
  }

  // Swap
  conversationId = result.conversation.id;
  conversationTitle = result.conversation.title;
  conversationCreatedAt = result.conversation.createdAt;
  titleAutoGenerated = false;
  titleManuallySet = !!result.conversation.title;
  messages.length = 0;
  messages.push(...result.conversation.messages.map(fromPersistedMessage));
  pendingAttachments.length = 0;
  state.error = null;
  state.pendingViolation = null;
  state.pendingAsk = null;

  // Final commit step — only after successful load
  await api.conversationSetActive(id);
}

export async function deleteConversation(id: string): Promise<void> {
  if (state.streaming && id === conversationId) return;

  await api.conversationDelete(id);

  // Remove from local list
  const idx = conversationList.findIndex(c => c.id === id);
  if (idx >= 0) conversationList.splice(idx, 1);

  if (id === conversationId) {
    // Clear so switchConversation won't re-save the deleted conversation
    messages.length = 0;
    if (conversationList.length > 0) {
      // Switch to most recent
      const sorted = [...conversationList].sort((a, b) => b.updatedAt - a.updatedAt);
      await switchConversation(sorted[0].id);
    } else {
      // Last deleted → unsaved blank
      conversationId = uuid();
      conversationTitle = '';
      conversationCreatedAt = Date.now();
      titleAutoGenerated = false;
      titleManuallySet = false;
      messages.length = 0;
      pendingAttachments.length = 0;
      state.error = null;
      state.pendingViolation = null;
      state.pendingAsk = null;
      await api.conversationSetActive(null);
    }
  }
}

export async function renameConversation(id: string, title: string): Promise<void> {
  if (state.streaming && id === conversationId) return;

  const result = await api.conversationRename(id, title);
  if (!result) return;

  // Update local list
  const idx = conversationList.findIndex(c => c.id === id);
  if (idx >= 0) {
    conversationList[idx] = result;
  }

  if (id === conversationId) {
    conversationTitle = title;
    titleAutoGenerated = false;
    titleManuallySet = true;
  }
}
